### ISSUE TITLE
IssuanceMessage should identify the target ServerUpdate

### ISSUE THREAD

**Issue by chris-wood** [alxdavids/privacy-pass-ietf#13]
... so that servers know clients are using the right key and haven't been downgraded, for whatever reason. In ECHO, we indicate this with a hash of the ECHOConfig structure, which would probably do the trick here, too. For example:

~~~
struct {
    uint8 update_digest[32];
     ClientIssuanceElement issue_element<1..n>
} IssuanceMessage;
~~~

where `update_digest = SHA256(server_update)`, or something.

**Comment by alxdavids** [comment]
The protocol doc now assumes that the ciphersuite is known apriori when retrieving the Server public key data.
