### ISSUE TITLE
Add "configuration" support

### ISSUE THREAD

**Issue by chris-wood** [alxdavids/privacy-pass-ietf#15]
The main protocol document assumes that VOPRF is the main instantiation of PrivacyPass. It also has support for ciphersuites that augment this particular instantiation. It's not clear how we'd "extend" this protocol to support other features, such as public verifiability or the k-bits of metadata. These seem to be separate "modes" or "configurations" of PrivacyPass. (I don't think it makes sense to try and cast the metadata bit variant as a different ciphersuite for the main instantiation.) 

I propose we add some text describing different configurations. A configuration is an instantiation of the PrivacyPass API with certain properties. A configuration may (should?) also be extensible where applicable, e.g., in the ServerUpdate message or IssuanceRequest/Response messages. Interoperability across configurations would be unsupported, as they have would like have fundamentally different properties.

Some initial configurations that come to mind are:
- PrivacyPass with no metadata bits (VOPRF construction)
- PrivacyPass with k metadata bits (Google's design)
- PrivacyPass with public verifiability (blind signatures?)

cc @alxdavids

**Comment by alxdavids** [comment]
Added some more information about supporting additional metadata in #32. As discussed elsewhere, I think the way to go here is for extensions to just specify new ciphersuites with associated privacy/security guarantees.
