### ISSUE TITLE
Should ServerUpdate messages be versioned?

### ISSUE THREAD

**Issue by chris-wood** [alxdavids/privacy-pass-ietf#16]
They don't currently have a version. That seems like something which would be good to add. Extension support seems useful, too, so we don't need to rev the version each time we need a small change.

**Comment by alxdavids** [comment]
ServerUpdate does not exist anymore. New extensions should just add a new ciphersuite to the current enum. A server that uses an extension ciphersuite just specifies the ciphersuite with their public key data.
