### ISSUE TITLE
Define version/configuration registry

### ISSUE THREAD

**Issue by chris-wood** [alxdavids/privacy-pass-ietf#21]
It might be easiest to fully specify a Privacy Pass configuration, e.g., "Privacy Pass based on curve448_hkdf_sha512_ell2_ro," with a single identifier. That same identifier could go in the `ServerUpdate` structure as a way of fully defining the properties of the structure.

**Comment by alxdavids** [comment]
Replaced Privacy Pass configuration with just a public key and associated ciphersuite. Changes to remove hard-coded key registry means that we don't have to be so prescriptive here anymore.
